---
- name: Ansible playbook for setting up image builder
  hosts: localhost
  gather_facts: yes
  tasks:
  - name: Include ansible vault secrets
    include_vars:
      file: "./vars/secrets.yml"
  - name: setup image builder
    ansible.builtin.include_role:
      name: rprakashg.demos.setup_imagebuilder
    vars:
      create_infra: true
      base_domain: "{{ base_domain }}"
      subdomain: "{{ subdomain }}"
      region: "{{ region }}"