name: CI workflow for building RHDE image with Microshift
on:
    workflow_dispatch:
jobs:
    build:
        name: Build image
        runs-on: self-hosted
        steps:
        - uses: actions/checkout@v3
        - name: Run playbook
          run: |
            echo "Running ansible playbook"
            ansible-playbook build-image.yml -e @rhde-with-microshift.yml
          shell: bash