---
name: Configure github actions runner
on:
    workflow_dispatch:
env:
  AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
  AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
  AWS_ACCOUNT_ID: ${{ secrets.AWS_ACCOUNT_ID }}
  AWS_DEFAULT_REGION: ${{ vars.AWS_DEFAULT_REGION }}

jobs:
    configure:
        name: Configure github actions runner
        runs-on: ubuntu-latest
        steps:
        - uses: actions/checkout@v3

        - name: Set up Python
          uses: actions/setup-python@v5
          with:
            python-version: '3.10'

        - name: Install Ansible
          run: |
            python -m pip install --upgrade pip
            pip install ansible

        - name: Add SSH private key
          run: |
            mkdir -p ~/.ssh
            echo "${{ secrets.ANSIBLE_SSH_PRIVATE_KEY }}" > ~/.ssh/ec2
            chmod 600 ~/.ssh/ec2
          shell: bash
        - name: Add SSH pub key
          run: |
            echo "${{ secrets.ANSIBLE_SSH_PUBLIC_KEY }}" > ~/.ssh/ec2.pub
            chmod 600 ~/.ssh/ec2.pub
          shell: bash

        - name: Install rprakashg.demos ansible collection
          run: |
            ansible-galaxy collection install git+https://github.com/rprakashg/demos.git,main
          shell: bash

        - name: Run playbook
          run: |
            echo "Running ansible playbook"
            ansible-playbook -i inventory --vault-password-file <(echo "$VAULT_SECRET") configure-gh-actions-runner.yml
          shell: bash
          env:
            ANSIBLE_HOST_KEY_CHECKING: false
            VAULT_SECRET: ${{ secrets.ANSIBLE_VAULT_PASSWORD }}
