---
name: setup image builder
on:
    workflow_dispatch:

jobs:
    setup:
        name: Setup image builder infra
        runs-on: ubuntu-latest
        steps:
        - uses: actions/checkout@v3
        - name: Set up Python
          uses: actions/setup-python@v5
          with:
            python-version: '3.10'
        - name: Install Ansible
          run: |
            python -m pip install --upgrade pip
            pip install ansible
